# Source: cluster-api-aws/templates/aws-machinetemplates-control-plane.yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AWSMachineTemplate
metadata:
  name: 0be9aaff-3ebf-471f-a6aa-6fdf94bcc98e-control-plane
  namespace: 0be9aaff-3ebf-471f-a6aa-6fdf94bcc98e
spec:
  template:
    spec:
      iamInstanceProfile: control-plane.cluster-api-provider-aws.sigs.k8s.io
      instanceType: t3.medium
      sshKeyName: tks-seoul
      rootVolume:
        size: 20
        type: gp2
